compile:
	g++ -std=c++11 Tester.cpp TestHttpRequestParser.cpp TestDBManager.cpp /home/hsenid/training/angularProj/library-management-system-backend/LibraryServer/src/HttpRequestParser.cpp /home/hsenid/training/angularProj/library-management-system-backend/LibraryServer/src/utils/DateUtils.cpp   /home/hsenid/training/angularProj/library-management-system-backend/LibraryServer/src/ConfigHandler.cpp  /home/hsenid/training/angularProj/library-management-system-backend/LibraryServer/src/notify/SMSNotifier.cpp /home/hsenid/training/angularProj/library-management-system-backend/LibraryServer/src/db/DBManager.cpp -o test -lgtest -lboost_system -lcrypto -lssl -lcpprest -I/usr/local/include/mongocxx/v_noabi -I/usr/local/include/libmongoc-1.0 -I/usr/local/include/bsoncxx/v_noabi -I/usr/local/include/libbson-1.0 -L/usr/local/lib -lmongocxx -lbsoncxx

execute:
	./test
